/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegistrationIndexRouteImport } from './routes/registration/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as ProfileUsernameRouteRouteImport } from './routes/profile/$username/route'
import { Route as ProfileUsernameIndexRouteImport } from './routes/profile/$username/index'
import { Route as ProfileUsernameCardsRouteImport } from './routes/profile/$username_.cards'
import { Route as ProfileUsernameEditRouteImport } from './routes/profile/$username/edit'

const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationIndexRoute = RegistrationIndexRouteImport.update({
  id: '/registration/',
  path: '/registration/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRouteRoute = ProfileUsernameRouteRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameIndexRoute = ProfileUsernameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileUsernameRouteRoute,
} as any)
const ProfileUsernameCardsRoute = ProfileUsernameCardsRouteImport.update({
  id: '/profile/$username_/cards',
  path: '/profile/$username/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameEditRoute = ProfileUsernameEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProfileUsernameRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/profile/$username': typeof ProfileUsernameRouteRouteWithChildren
  '/profile': typeof ProfileIndexRoute
  '/registration': typeof RegistrationIndexRoute
  '/profile/$username/edit': typeof ProfileUsernameEditRoute
  '/profile/$username/cards': typeof ProfileUsernameCardsRoute
  '/profile/$username/': typeof ProfileUsernameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileIndexRoute
  '/registration': typeof RegistrationIndexRoute
  '/profile/$username/edit': typeof ProfileUsernameEditRoute
  '/profile/$username/cards': typeof ProfileUsernameCardsRoute
  '/profile/$username': typeof ProfileUsernameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/profile/$username': typeof ProfileUsernameRouteRouteWithChildren
  '/profile/': typeof ProfileIndexRoute
  '/registration/': typeof RegistrationIndexRoute
  '/profile/$username/edit': typeof ProfileUsernameEditRoute
  '/profile/$username_/cards': typeof ProfileUsernameCardsRoute
  '/profile/$username/': typeof ProfileUsernameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/profile/$username'
    | '/profile'
    | '/registration'
    | '/profile/$username/edit'
    | '/profile/$username/cards'
    | '/profile/$username/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/profile'
    | '/registration'
    | '/profile/$username/edit'
    | '/profile/$username/cards'
    | '/profile/$username'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/profile/$username'
    | '/profile/'
    | '/registration/'
    | '/profile/$username/edit'
    | '/profile/$username_/cards'
    | '/profile/$username/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  ProfileUsernameRouteRoute: typeof ProfileUsernameRouteRouteWithChildren
  ProfileIndexRoute: typeof ProfileIndexRoute
  RegistrationIndexRoute: typeof RegistrationIndexRoute
  ProfileUsernameCardsRoute: typeof ProfileUsernameCardsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration/': {
      id: '/registration/'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username/': {
      id: '/profile/$username/'
      path: '/'
      fullPath: '/profile/$username/'
      preLoaderRoute: typeof ProfileUsernameIndexRouteImport
      parentRoute: typeof ProfileUsernameRouteRoute
    }
    '/profile/$username_/cards': {
      id: '/profile/$username_/cards'
      path: '/profile/$username/cards'
      fullPath: '/profile/$username/cards'
      preLoaderRoute: typeof ProfileUsernameCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username/edit': {
      id: '/profile/$username/edit'
      path: '/edit'
      fullPath: '/profile/$username/edit'
      preLoaderRoute: typeof ProfileUsernameEditRouteImport
      parentRoute: typeof ProfileUsernameRouteRoute
    }
  }
}

interface ProfileUsernameRouteRouteChildren {
  ProfileUsernameEditRoute: typeof ProfileUsernameEditRoute
  ProfileUsernameIndexRoute: typeof ProfileUsernameIndexRoute
}

const ProfileUsernameRouteRouteChildren: ProfileUsernameRouteRouteChildren = {
  ProfileUsernameEditRoute: ProfileUsernameEditRoute,
  ProfileUsernameIndexRoute: ProfileUsernameIndexRoute,
}

const ProfileUsernameRouteRouteWithChildren =
  ProfileUsernameRouteRoute._addFileChildren(ProfileUsernameRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  ProfileUsernameRouteRoute: ProfileUsernameRouteRouteWithChildren,
  ProfileIndexRoute: ProfileIndexRoute,
  RegistrationIndexRoute: RegistrationIndexRoute,
  ProfileUsernameCardsRoute: ProfileUsernameCardsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
